services:
  compliance:
    build:
      context: .
      dockerfile: Dockerfile.compliance

    env_file:
      - .env

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp-sa.json

    volumes:
      - ./adk-agent-key.json:/secrets/gcp-sa.json:ro

    ports:
      - "8001:8001"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api

    env_file:
      - .env

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp-sa.json
      GOOGLE_GENAI_USE_VERTEXAI: "true"

    volumes:
      - ./adk-agent-key.json:/secrets/gcp-sa.json:ro

    depends_on:
      - compliance

    ports:
      - "8000:8000"


  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    environment:
      API_BASE_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"
